### ISSUE TITLE
在Folia下运行会报错

### ISSUE THREAD

**Issue by mangocraft** [DreamVoid/MiraiMCAddon-Overflow#1]
在Folia下运行会报错
报错内容：
Error occurred while enabling MiraiMCAddon-Overflow v1.0 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.handle(CraftScheduler.java:524) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:252) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:239) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:190) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:159) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at org.bukkit.scheduler.BukkitRunnable.runTaskAsynchronously(BukkitRunnable.java:63) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at MiraiMCAddon-Overflow.jar/me.dreamvoid.miraimcaddon.overflow.BukkitPlugin.connect(BukkitPlugin.java:91) ~[MiraiMCAddon-Overflow.jar:?]
        at MiraiMCAddon-Overflow.jar/me.dreamvoid.miraimcaddon.overflow.BukkitPlugin.onEnable(BukkitPlugin.java:37) ~[MiraiMCAddon-Overflow.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:595) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:780) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:527) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:331) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[luminol-1.21.jar:1.21-DEV-d01eef5]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[03:54:22 INFO]: [MiraiMCAddon-Overflow] Disabling MiraiMCAddon-Overflow v1.0

**Comment by DreamVoid** [comment]
本插件用到了paper已移除的BukkitScheduler，有能力可以自行修改代码使用paper推的AsyncScheduler

**Comment by mangocraft** [comment]
> 本插件用到了paper已移除的BukkitScheduler，有能力可以自行修改代码使用paper推的AsyncScheduler

经测试人仍然会报错
[11:00:34 INFO]: [MiraiMC] Calling MiraiMC to load Overflow core.
[11:00:35 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'MiraiMCAddon-Overflow.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `me.dreamvoid.miraimcaddon.overflow.BukkitPlugin'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:106) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:552) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:294) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: https://s01.oss.sonatype.org/content/repositories/snapshots/top/mrxiaom/overflow-core-all/2.16.0-e2ed65e-SNAPSHOT/maven-metadata.xml
        at MiraiMCAddon-Overflow.jar/me.dreamvoid.miraimcaddon.overflow.BukkitPlugin.<init>(BukkitPlugin.java:34) ~[MiraiMCAddon-Overflow.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.io.FileNotFoundException: https://s01.oss.sonatype.org/content/repositories/snapshots/top/mrxiaom/overflow-core-all/2.16.0-e2ed65e-SNAPSHOT/maven-metadata.xml
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2007) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1602) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[?:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.Utils$Http.get(Utils.java:132) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.loader.LibraryLoader.getSnapshotJarUrl(LibraryLoader.java:173) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.loader.LibraryLoader.getJarUrl(LibraryLoader.java:165) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.loader.LibraryLoader.loadLibraryMaven(LibraryLoader.java:86) ~[MiraiMC-Bukkit.jar:?]
        at MiraiMCAddon-Overflow.jar/me.dreamvoid.miraimcaddon.overflow.BukkitPlugin.<init>(BukkitPlugin.java:31) ~[MiraiMCAddon-Overflow.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more

**Comment by DreamVoid** [comment]
> > 本插件用到了paper已移除的BukkitScheduler，有能力可以自行修改代码使用paper推的AsyncScheduler
> 
> 经测试人仍然会报错
> [11:00:34 INFO]: [MiraiMC] Calling MiraiMC to load Overflow core.
> [11:00:35 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'MiraiMCAddon-Overflow.jar' in folder 'plugins\.paper-remapped'
> org.bukkit.plugin.InvalidPluginException: Exception initializing main class `me.dreamvoid.miraimcaddon.overflow.BukkitPlugin'
>         at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:106) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
>         at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
>         at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
>         at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
>         at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
>         at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:552) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:294) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[luminol-1.21.1.jar:1.21.1-DEV-065b78f]
>         at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
> Caused by: java.lang.reflect.InvocationTargetException
>         at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
>         at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
>         ... 10 more
> Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: https://s01.oss.sonatype.org/content/repositories/snapshots/top/mrxiaom/overflow-core-all/2.16.0-e2ed65e-SNAPSHOT/maven-metadata.xml
>         at MiraiMCAddon-Overflow.jar/me.dreamvoid.miraimcaddon.overflow.BukkitPlugin.<init>(BukkitPlugin.java:34) ~[MiraiMCAddon-Overflow.jar:?]
>         at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
>         at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
>         ... 10 more
> Caused by: java.io.FileNotFoundException: https://s01.oss.sonatype.org/content/repositories/snapshots/top/mrxiaom/overflow-core-all/2.16.0-e2ed65e-SNAPSHOT/maven-metadata.xml
>         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2007) ~[?:?]
>         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1602) ~[?:?]
>         at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[?:?]
>         at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.Utils$Http.get(Utils.java:132) ~[MiraiMC-Bukkit.jar:?]
>         at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.loader.LibraryLoader.getSnapshotJarUrl(LibraryLoader.java:173) ~[MiraiMC-Bukkit.jar:?]
>         at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.loader.LibraryLoader.getJarUrl(LibraryLoader.java:165) ~[MiraiMC-Bukkit.jar:?]
>         at MiraiMC-Bukkit.jar/me.dreamvoid.miraimc.internal.loader.LibraryLoader.loadLibraryMaven(LibraryLoader.java:86) ~[MiraiMC-Bukkit.jar:?]
>         at MiraiMCAddon-Overflow.jar/me.dreamvoid.miraimcaddon.overflow.BukkitPlugin.<init>(BukkitPlugin.java:31) ~[MiraiMCAddon-Overflow.jar:?]
>         at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
>         at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
>         ... 10 more

自行检查你的服务器网络问题

**Comment by mangocraft** [comment]
重新尝试后遇到了新的报错：
[11:32:43 INFO]: [MiraiMC] Calling MiraiMC to load Overflow core.
[11:32:43 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'MiraiMCAddon-Overflow.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `me.dreamvoid.miraimcaddon.overflow.BukkitPlugin'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:106) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:553) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:294) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:356) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.NoSuchMethodError: 'me.dreamvoid.miraimc.Platform me.dreamvoid.miraimc.LifeCycle.getPlatform()'
        at MiraiMCAddon-Overflow.jar/me.dreamvoid.miraimcaddon.overflow.BukkitPlugin.<init>(BukkitPlugin.java:29) ~[MiraiMCAddon-Overflow.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more

**Comment by DreamVoid** [comment]
> 重新尝试后遇到了新的报错： [11:32:43 INFO]: [MiraiMC] Calling MiraiMC to load Overflow core. [11:32:43 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'MiraiMCAddon-Overflow.jar' in folder 'plugins.paper-remapped' org.bukkit.plugin.InvalidPluginException: Exception initializing main class `me.dreamvoid.miraimcaddon.overflow.BukkitPlugin' at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:106) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d] at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d] at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d] at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d] at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:553) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:294) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:356) ~[luminol-1.21.1.jar:1.21.1-DEV-6825d1d] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] Caused by: java.lang.reflect.InvocationTargetException at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?] at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?] ... 10 more Caused by: java.lang.NoSuchMethodError: 'me.dreamvoid.miraimc.Platform me.dreamvoid.miraimc.LifeCycle.getPlatform()' at MiraiMCAddon-Overflow.jar/me.dreamvoid.miraimcaddon.overflow.BukkitPlugin.(BukkitPlugin.java:29) ~[MiraiMCAddon-Overflow.jar:?] at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?] ... 10 more

全部更新最新开发版

**Comment by mangocraft** [comment]
MiraiMC已经是能在action里下的最新版本了（[eb13c17] 
5 days ago）

**Comment by DreamVoid** [comment]
> MiraiMC已经是能在action里下的最新版本了（[eb13c17] 5 days ago）

本插件呢？也是1.1版本吗？

**Comment by mangocraft** [comment]
> > MiraiMC已经是能在action里下的最新版本了（[eb13c17] 5 days ago）
> 
> 本插件呢？也是1.1版本吗？

是的
