### ISSUE TITLE
在nukkit上运行会报错

### ISSUE THREAD

**Issue by AceBenX** [DreamVoid/MiraiMCAddon-Overflow#3]
14:08:41 [ERROR] Throwing
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43) ~[server.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.getClassByName(JavaPluginLoader.java:147) ~[server.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:39) ~[server.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27) ~[server.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:47) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:114) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:254) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:151) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:143) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:139) ~[server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:712) ~[server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:87) [server.jar:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43) ~[server.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27) ~[server.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 22 more

**Comment by DreamVoid** [comment]
谁告诉你这是nukkit用的

**Comment by AceBenX** [comment]
抱歉，请问该如何使用这个插件

**Comment by AceBenX** [comment]
抱歉，请问该如何使用
